apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "otus-microsrv-hw3.fullname" . }}-{{ .Release.Revision }}
  labels:
    {{- include "otus-microsrv-hw3.labels" . | nindent 4 }}
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        {{- include "otus-microsrv-hw3.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "otus-microsrv-hw3.serviceAccountName" . }}   
      containers:
      - name: {{ .Chart.Name }}-job        
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["dotnet"]
        args: ["UserApi.dll", "-m"]
        envFrom:
            - configMapRef:
                 name: hw3-config 
            - secretRef:
                 name: hw3-secrets
      restartPolicy: {{ .Values.job.restartPolicy }}