{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "otus-microsrv-hw3.fullname" . }}
  labels:
    {{- include "otus-microsrv-hw3.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "otus-microsrv-hw3.fullname" . }}
  namespaceSelector:
    matchNames:
    - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "otus-microsrv-hw3.selectorLabels" . | nindent 6 }}
  endpoints:
  - interval: 15s
    port: http
    path: /metrics
{{- end }}