postgresqlDatabase: "users"
postgresqlUsername: "postgres"
postgresqlPassword: "postgres"
service:
  port: "5432"
persistence:
  size: 1Gi
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  extraEnvVars:
    - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
      value: "true"