{
 "title": "HW3",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "RPS & Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App: RPS: total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum\r\n(rate(app_request_count[1m]))",
     "legendFormat": "RPS: {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Nginx: RPS: total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum\r\n(rate(nginx_ingress_controller_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "App: RPS: /users.*",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (exported_endpoint, method) \r\n(rate(app_request_count{exported_endpoint=~\"/users.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Nginx: RPS: /users.*",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (path, method)\r\n(rate(nginx_ingress_controller_request_duration_seconds_count{path=~\"/users.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "App: Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(app_request_count{http_status=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Nginx: Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "App: Latency 0,5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (exported_endpoint, method, le)(rate(app_request_latency_seconds_bucket{exported_endpoint=~\"/users.*\"}[1m]))))"
    }
   ]
  },
  {
   "title": "Nginx: Latency 0,5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (path, method, le)(rate(nginx_ingress_controller_request_duration_seconds_bucket{path=~\"/users.*\"}[1m]))))"
    }
   ]
  },
  {
   "title": "App: Latency 0,95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, (sum by (exported_endpoint, method, le)(rate(app_request_latency_seconds_bucket{exported_endpoint=~\"/users.*\"}[1m]))))"
    }
   ]
  },
  {
   "title": "Nginx: Latency 0,95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, (sum by (path, method, le)(rate(nginx_ingress_controller_request_duration_seconds_bucket{path=~\"/users.*\"}[1m]))))"
    }
   ]
  },
  {
   "title": "App: Latency 0,99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (sum by (exported_endpoint, method, le)(rate(app_request_latency_seconds_bucket{exported_endpoint=~\"/users.*\"}[1m]))))"
    }
   ]
  },
  {
   "title": "Nginx: Latency 0,99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (sum by (path, method, le)(rate(nginx_ingress_controller_request_duration_seconds_bucket{path=~\"/users.*\"}[1m]))))"
    }
   ]
  },
  { "title": "Pod restarts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "resets(app_request_count{exported_endpoint=\"/users\"}[1m])"
    }
   ]
  },
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "PG Number of available connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sum by (server) (pg_settings_max_connections) - sum by (server) (pg_settings_superuser_reserved_connections) - sum by (server) (pg_stat_activity_count)) / sum by (server) (pg_settings_max_connections)) * 100"
    }
   ]
  },
  {
   "title": "PG is running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    { "expr": "pg_up" }
   ]
  },
  {
   "title": "PG Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration*1000"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=\"\", namespace=\"hw3\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"\", namespace=\"hw3\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"\", namespace=\"hw3\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"hw3\", container!=\"\", image!=\"\"}) by (pod)"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"\", namespace=\"hw3\", type=\"hard\",resource=\"requests.memory\"})"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"\", namespace=\"hw3\", type=\"hard\",resource=\"limits.memory\"})"
    }
   ]
  }
 ]
}