apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: migration-reader
rules:
  - apiGroups: ["batch","extensions", ""]
    resources: ["jobs", "pods"]
    verbs: ["get","watch","list"]